services:
  postgres:
    image: postgres:16
    container_name: logistics_postgres_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-logistics}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

  backend:
    build: ./backend
    container_name: logistics_backend_prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app # Useful for hotfix but preferably remove for pure prod immutability
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:5432/${POSTGRES_DB:-logistics}
      JWT_SECRET: ${JWT_SECRET:-changethisforproduction}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      FRONTEND_URL: ${FRONTEND_URL:-https://puretrack.cloud}
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always

  frontend:
    build: ./frontend
    container_name: logistics_frontend_prod
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: /api
    networks:
      - app_network
    restart: always

volumes:
  postgres_data_prod:


networks:
  app_network:
    driver: bridge
